from tkinter import *
window = Tk()
window.title("Transmission Simulation")
window.geometry('800x600')
lbl = Label(window ,text= "Enter the Number of Nodes")
lbl.grid(column=0, row=0)
spin = Spinbox(window, from_=0, to=100, width=20)
spin.grid(column=1,row=0)
lbl = Label(window ,text= "Enter the Number of Time Slots")
lbl.grid(column=0, row=1)
spin = Spinbox(window, from_=0, to=100, width=20)
spin.grid(column=1,row=1)
lbl = Label(window ,text= "Enter the Buffer Size")
lbl.grid(column=0, row=2)
spin = Spinbox(window, from_=0, to=100, width=20)
spin.grid(column=1,row=2)
lbl = Label(window ,text= "Enter the Probability of Generating Packet")
lbl.grid(column=0, row=3)
spin = Spinbox(window, from_=0, to=100, width=20)
spin.grid(column=1,row=3)
window.mainloop()

#NumberOfNodes = input("Enter the Number of Nodes\n")
#NumberOfBufferSize = input("Enter the Buffer Size\n")
#NumberOfTimeSlot = input("Enter Number of Time Slot\n")
#ProbabilityValueOfGeneratingPackets = input("Enter the Probability of Generating Packets\n")
